/**
 * router.js — Auto-mounting route loader
 *
 * Scans server/src/features/*&#47;*.routes.js and mounts each route file.
 * Team members: add a new *.routes.js inside your feature folder.
 * DO NOT edit this file to add new routes — it happens automatically.
 */

const path = require('path');
const fs = require('fs');

/**
 * Recursively find all *.routes.js files under featuresDir
 */
function findRouteFiles(dir) {
  let results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(findRouteFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith('.routes.js')) {
      results.push(fullPath);
    }
  }
  return results;
}

function mountRoutes(app) {
  const featuresDir = path.join(__dirname, '..', 'features');

  if (!fs.existsSync(featuresDir)) {
    console.warn('[router] No features directory found — skipping route mount.');
    return;
  }

  const routeFiles = findRouteFiles(featuresDir);

  routeFiles.forEach((filePath) => {
    const routeModule = require(filePath);
    if (routeModule && routeModule.router && routeModule.prefix) {
      app.use(routeModule.prefix, routeModule.router);
      console.log(`[router] Mounted: ${routeModule.prefix} → ${path.relative(process.cwd(), filePath)}`);
    } else {
      console.warn(`[router] Skipped (missing .router or .prefix export): ${filePath}`);
    }
  });
}

module.exports = mountRoutes;
