-- Migration: 003_create_energy_plans
-- Purpose: Store the optimized 24-hour energy plans generated by the optimizer
-- Rule: Never modify this file after it has been applied to any environment.

CREATE TABLE IF NOT EXISTS energy_plans (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scenario_id       UUID NOT NULL REFERENCES energy_scenarios(scenario_id)
                      ON DELETE CASCADE,

  -- Optimization result
  status            TEXT NOT NULL DEFAULT 'success'
                      CHECK (status IN ('success', 'error', 'partial')),
  hourly_plan       JSONB NOT NULL,           -- Array of 24 HourlyPlanEntry objects
  total_cost        NUMERIC(12, 4),           -- Total energy cost in USD

  -- Summary metrics
  total_grid_import_kwh   NUMERIC(12, 4),
  total_grid_export_kwh   NUMERIC(12, 4),
  total_solar_used_kwh    NUMERIC(12, 4),
  peak_demand_kw          NUMERIC(10, 4),
  battery_cycles_used     NUMERIC(6, 4),
  objectives_met          TEXT[],             -- Array of achieved objective strings

  -- Metadata
  optimized_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  optimizer_version TEXT DEFAULT '1.0.0'
);

-- Index for fast lookup
CREATE INDEX IF NOT EXISTS idx_energy_plans_scenario_id
  ON energy_plans (scenario_id);

CREATE INDEX IF NOT EXISTS idx_energy_plans_optimized_at
  ON energy_plans (optimized_at DESC);

COMMENT ON TABLE energy_plans IS
  'Optimized 24-hour energy schedules produced by the optimizer module.';

COMMENT ON COLUMN energy_plans.hourly_plan IS
  'JSONB array of HourlyPlanEntry: { hour, grid_import_kw, grid_export_kw, battery_charge_kw, battery_discharge_kw, battery_soc_kwh, cost_usd, source_mix }';
